name: Notify Slack with Date

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # UTC 기준, 매일 오전 6시에 실행 (한국시간 오후 3시)
  
jobs:
  send-slack-message:
    runs-on: ubuntu-latest
    steps:
      # 1. 현재 날짜를 환경 변수에 저장
      - name: Set current date
        run: echo "CURRENT_DATE=$(date '+%m/%d')" >> $GITHUB_ENV

      # 2. Python 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. Python 의존성 설치
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4. Python 스크립트 실행
      - name: Run main.py
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          CURRENT_DATE: ${{ env.CURRENT_DATE }}
        run: python3 main.py
